### ISSUE TITLE
Missing the file "generation.json" for execution-based evaluation and Cannot load CodeT5

### ISSUE THREAD

**Issue by tuanqdinh** [mahimanzum/FixEval#4]
Hi, I cannot file generation.json in the data folder. Can you please check if it is available?
Also, the provided CodeT5 checkpoint doesn't match the model code (some key mismatches).

**Comment by mahimanzum** [comment]
Hello,
If you want to use the pretrained model and generation.json files just download them from [[Here](https://drive.google.com/drive/folders/1dzuHuouuWzlFCy1CMj9DYG9JGraEay27?usp=sharing)] . Download the Codet5.zip file. Regarding the checkpoint I just did the same thing and the checkpoint was working fine. There are some extra keys that the transformer library adds but overall there are no key mismatches. I revised the readme with better instructions. Hope this helps.
