### ISSUE TITLE
Could you provide the problem statement associated with each task?

### ISSUE THREAD

**Issue by Ji4chenLi** [mahimanzum/FixEval#5]
Hi,

Thanks for the great work! Could you provide the problem statement associated with each task as shown in the Figure 1?

![image](https://github.com/user-attachments/assets/652e2952-46e3-43af-9d99-b1d61e3bcb61)

Thanks,
Jiachen

**Comment by mahimanzum** [comment]
Hello,
As far as I remember that is not directly available. You need to use the problem_list.csv file and create a link for each of the problems that crawl from the website or use the api's (not sure if the oj's used here provide API's) to get that.

**Comment by Ji4chenLi** [comment]
Got it. Thank you for your timely response!

**Comment by Ji4chenLi** [comment]
Btw, do you think if you could crawl these problem statement for us : )

I think it would significantly increase the impact of your work if you could provide the `problem statement` associated with the buggy and correct codes.

**Comment by wasiahmad** [comment]
@Ji4chenLi Traditional bug fixing tasks do not use any `problem statement`, so we skipped mining it. But since all the data are public, you should be able to collect it pretty easily.
